### ISSUE TITLE
不愿意开源就别开

### ISSUE THREAD

**Issue by WuZheBao0914** [tsingqguo/robustOT#2]
这作者Guo Tsing的论文包括SPARK、LRR都是这样子，不愿意开源可以不开，没必要放一个不完整的项目在这里浪费别人的时间和精力。
LRR: LANGUAGE-DRIVEN RESAMPLABLE CONTINUOUS REPRESENTATION AGAINST ADVERSARIAL TRACKING ATTACKS
SPARK: Spatial-aware Online Incremental Attack Against Visual Tracking

**Comment by tsingqguo** [comment]
你好，LRR 如果code问题请直接提出。这部分code已经超过了LRR 本身，准备集成其他code。SPARK code 在很多其他论文也进行了复现。我邮箱账号没同步，没及时看到问题，请见谅。

**Comment by WuZheBao0914** [comment]
感谢您的回复！关于LRR的问题，我有如下疑问：在testing时，需要运行$ROBOT_ROOT/scripts/test.py。但是在整个项目里却没办法找到scripts/test.py文件。请问是我对ROBOT_ROOT这个目录的设置有问题，还是在上传时缺失了这个文件夹的内容呢？

**Comment by jlc396** [comment]
Sorry for any confusion caused. The framework robustOT is a new project we're currently developing, and it is still a work in progress.

Regarding the implementation of `LRR`, we have indeed [included](https://github.com/tsingqguo/robustOT/tree/main/robustot/libs/LRR) it in the repository. However, since robustOT serves more as a library, the current state of the framework may too minimal for tasks like quickly testing `LRR`. To address this, we've uploaded the original `LRR` implementation in the branch [lrr_archived](https://github.com/tsingqguo/robustOT/tree/lrr_archived), which you can reference.
